name: Pull Request Build & Test

on: pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test and Build
        run: |
          yarn
          yarn lint
          yarn test
          yarn build
