name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Test and Build
        run: |
          yarn
          yarn lint
          yarn test
          yarn build
      # TODO: release
